### ISSUE TITLE
Deploy to Platform.sh

### ISSUE THREAD

**Issue by GuGuss** [rauchg/slackin#139]
Hi,

It's also possible to deploy to [Platform.sh](https://platform.sh). 

The only file required in the Git repository is a ``.platform.app.yaml``:
```
name: node

type: nodejs

web:
  commands:
    start: "./node_modules/.bin/slackin TEAM-ID TOKEN --channels 'CHANNEL,' --port $PORT"
  locations:
    "/":
      root: "public"
      passthru: true
      expires: 2h

hooks:
  build:
    npm install slackin

disk: 512
```

This will automatically download, deploy and configure the slackin application to [Platform.sh](https://platform.sh).

You can see a working example on [chat.platform.sh](http://chat.platform.sh/)
