### ISSUE TITLE
Bluemix setup does not work

### ISSUE THREAD

**Issue by rshriram** [rauchg/slackin#213]
Hi,
 The 'Deploy to Bluemix' button that you have does not result in a successful bluemix deployment. The app continues to crash for some unknown reason
`App instance exited with guid xxx payload: {"cc_partition"=>"default", "droplet"=>"xxx", "version"=>"xxx", "instance"=>"xxx", "index"=>0, "reason"=>"CRASHED", "exit_status"=>-1, "exit_description"=>"failed to start", "crash_timestamp"=>1467989560}`

I did change the defaults and set the org and token names, but still no dice.

On the other hand, the following very simple setup worked right out of the box for me. So you might want to update the bluemix deployment instructions. You just need two files:

manifest.yml:

``` yaml
applications:
- path: .
  memory: 256M
  instances: 1
  domain: mybluemix.net
  name: slackin-foo
  host: slackin-foo
  disk_quota: 1024M
```

and a package.json:

`````` json
{
  "name": "slackin-foo",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "slackin org token"
  },
  "dependencies": {
    "cfenv": "1.0.x",
    "express": "4.13.x",
    "slackin": "^0.8.3"
  },
  "repository": {},
  "engines": {
    "node": "4.x"
  }
}```

put them in a folder and do `cf push`. That should create the slackin-foo app automatically and launch it in Bluemix Cloud Foundry.
``````
